export const TRANSACTION_REASONS = [
  "Audit Fees and expenses",
  "Bank charges",
  "Capital item purchase",
  "Consumable purchase",
  "Corpus donation",
  "CSR Grant",
  "Donation",
  "Donation for SP",
  "Donation for Teachers Day Celebrations",
  "Donation GGB",
  "Edu Aid Purchase",
  "Event Expenditure",
  "General expenses",
  "Girls Hostel expenses",
  "Grant received",
  "Honorarium",
  "Internship fees",
  "Loan refund",
  "Loan received",
  "Maintenance charges",
  "Membership fees",
  "Office expenses",
  "Others", // Important trigger
  "Prizes/Gifts purchase",
  "Project expenses",
  "Raw materials purchase",
  "Refreshments",
  "Refund",
  "Rent paid",
  "Sahaaj Pathshalas expenses",
  "Sahaaj Poshan",
  "Salary",
  "Senior Citizen Care Project",
  "SP Tutor Honorarium",
  "Sponsorship",
  "Stipend",
  "Stitching, etc",
  "Student support",
  "Teachers day expenses",
  "To Identify",
  "Training expenses",
  "Training fees received",
  "Travelling expenses",
];
