export const dummyCentres = [
  {
    centre_id: "sp01",
    name: "Vijaya Gardens Sahaaj Pathsala, Baridih, Jamshedpur",
    street_address: "Baridih, Jamshedpur",
    city: "Jamshedpur",
    district: "East Singhbhum",
    state: "Jharkhand",
    pincode: "831017",
    status: "Inactive",
    date_associated: "2024-02-01",
    date_left: "2025-06-10",
  },
  {
    centre_id: "sp02",
    name: "Vijaya Gardens Sahaaj Pathsala, Baridih Jamshedpur",
    street_address: "Baridih, Jamshedpur",
    city: "Jamshedpur",
    district: "East Singhbhum",
    state: "Jharkhand",
    pincode: "831017",
    status: "Active",
    date_associated: "2025-06-01",
    date_left: null,
  },
  {
    centre_id: "sp03",
    name: "Vijaya Gardens Sahaaj Pathsala, Baridih Jamshedpur",
    street_address: "Baridih Jamshedpur",
    city: "Jamshedpur",
    district: "East Singhbhum",
    state: "Jharkhand",
    pincode: "831017",
    status: "Inactive",
    date_associated: "2019-06-01",
    date_left: "2025-05-27",
  },
  {
    centre_id: "sp04",
    name: "Vijaya Gardens Sahaaj Pathsala, Baridih Jamshedpur",
    street_address: "Baridih Jamshedpur",
    city: "Jamshedpur",
    district: "East Singhbhum",
    state: "Jharkhand",
    pincode: "831017",
    status: "Active",
    date_associated: "2024-08-01",
    date_left: null,
  },
];
