export const dummyClassrooms = [
  {
    classroom_id: "C01",
    centre_name: "Vijaya Gardens Sahaaj Pathsala, Baridih, Jamshedpur",
    section_code: "Junior",
    monthly_allowance: 1000,
    timing: "Evening",
    status: "Inactive",
    date_created: "2023-02-01",
    date_closed: "2025-07-10",
  },
  {
    classroom_id: "C02",
    centre_name: "Vijaya Gardens Sahaaj Pathsala, Baridih, Jamshedpur",
    section_code: "Junior",
    monthly_allowance: 1000,
    timing: "Evening",
    status: "Inactive",
    date_created: "2024-02-01",
    date_closed: "2025-06-10",
  },
  {
    classroom_id: "C03",
    centre_name: "Vijaya Gardens Sahaaj Pathsala, Baridih Jamshedpur",
    section_code: "Junior",
    monthly_allowance: 1000,
    timing: "Evening",
    status: "Active",
    date_created: "2025-06-01",
    date_closed: null,
  },
  {
    classroom_id: "C04",
    centre_name: "Vijaya Gardens Sahaaj Pathsala, Baridih Jamshedpur",
    section_code: "Senior",
    monthly_allowance: 1500,
    timing: "Evening",
    status: "Inactive",
    date_created: "2019-06-01",
    date_closed: "2025-05-27",
  },
  {
    classroom_id: "C05",
    centre_name: "Vijaya Gardens Sahaaj Pathsala, Baridih Jamshedpur",
    section_code: "Senior",
    monthly_allowance: 1500,
    timing: "Evening",
    status: "Active",
    date_created: "2024-08-01",
    date_closed: null,
  },
];
